project:
  type: website

website:
  title: "GeoCovid Buenos Aires"
  favicon: "images/geocovid_bsas_favicon.png"
  site-url: https://fernandez-lab-wsu.github.io/geocovid_bsas/
  page-navigation: true
  navbar:
    search: true
    logo: "images/geocovid_bsas_logo.png"
    left:
      - href: index.qmd
        text: LEEME
      - text: "Archivos del proyecto"
        menu:
          - creacion_mapa_bsas.qmd
          - analisis_datos_covid.qmd
          - creacion_de_rasters.qmd
          - calculo_movilidad_por_departamento.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: true
