{
  "hash": "c478820bdf8e41c2c023f8b9c89797b3",
  "result": {
    "markdown": "---\ntitle: \"Análisis de datos de COVID-19\"\nlang: es\n---\n\n\n\n---\n\n**Input inicial**\nBase de datos `csv` pública de casos de COVID-19 en Argentina.\n\n**Objetivo**\nObtener una base de datos limplia y lista de usar en GeoCovid app:\n- Cada observación debe tener una fecha de contagio/enfermedad.\n\n---\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.2     ✔ readr     2.1.4\n✔ forcats   1.0.0     ✔ stringr   1.5.0\n✔ ggplot2   3.4.3     ✔ tibble    3.2.1\n✔ lubridate 1.9.2     ✔ tidyr     1.3.0\n✔ purrr     1.0.1     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n\nAttaching package: 'arrow'\n\n\nThe following object is masked from 'package:lubridate':\n\n    duration\n\n\nThe following object is masked from 'package:utils':\n\n    timestamp\n\n\n\nAttaching package: 'plotly'\n\n\nThe following object is masked from 'package:arrow':\n\n    schema\n\n\nThe following object is masked from 'package:ggplot2':\n\n    last_plot\n\n\nThe following object is masked from 'package:stats':\n\n    filter\n\n\nThe following object is masked from 'package:graphics':\n\n    layout\n```\n:::\n:::\n\n\n## Carga de los datos y análisis inicial\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Leo el archivo como csv. Esta en Dropbox ya que es bastante grande.\ncovid_data <- arrow::open_dataset(\"/Users/florenciadandrea/Dropbox/data_geocovid/Covid19Casos.csv\", \n                           format = 'csv')\n\n# Elijo que datos voy a descargar usando dplyr. \n# Los datos no se bajan hasta que uso collect()\n\ncovid_casos_muestra <- covid_data |> \n  filter(clasificacion_resumen != 'Descartado',\n         carga_provincia_nombre %in% c('CABA', 'Buenos Aires') | residencia_provincia_nombre %in% c('CABA', 'Buenos Aires')) |>\n  select(id_evento_caso,\n          edad, edad_años_meses, sexo,\n          carga_provincia_nombre,\n          residencia_pais_nombre, residencia_provincia_nombre, residencia_departamento_nombre,\n          fecha_inicio_sintomas, fecha_diagnostico, fecha_internacion, fecha_cui_intensivo, fecha_fallecimiento,\n          clasificacion, clasificacion_resumen) |> \n  collect()\n\n# Los guardo en formato parquet para reducir el tamaño\n# write_parquet(covid_casos_muestra, \"../data/covid_casos/covid_casos_baires.parquet\")\n```\n:::\n\n\nComposición del dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid_casos_muestra <- read_parquet(\"data/inicial/covid_casos_baires.parquet\")\nstr(covid_casos_muestra)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntibble [5,245,880 × 15] (S3: tbl_df/tbl/data.frame)\n $ id_evento_caso                : int [1:5245880] 10000049 10000055 10000057 1000006 10000066 10000076 10000079 10000084 10000087 10000093 ...\n $ edad                          : int [1:5245880] 74 43 36 30 44 46 55 47 45 48 ...\n $ edad_años_meses               : chr [1:5245880] \"Años\" \"Años\" \"Años\" \"Años\" ...\n $ sexo                          : chr [1:5245880] \"F\" \"F\" \"M\" \"M\" ...\n $ carga_provincia_nombre        : chr [1:5245880] \"CABA\" \"CABA\" \"Buenos Aires\" \"Buenos Aires\" ...\n $ residencia_pais_nombre        : chr [1:5245880] \"Argentina\" \"Argentina\" \"Argentina\" \"Argentina\" ...\n $ residencia_provincia_nombre   : chr [1:5245880] \"CABA\" \"CABA\" \"Buenos Aires\" \"Buenos Aires\" ...\n $ residencia_departamento_nombre: chr [1:5245880] \"COMUNA 09\" \"COMUNA 09\" \"Mercedes\" \"Malvinas Argentinas\" ...\n $ fecha_inicio_sintomas         : Date[1:5245880], format: NA NA ...\n $ fecha_diagnostico             : Date[1:5245880], format: \"2021-04-10\" \"2021-04-14\" ...\n $ fecha_internacion             : Date[1:5245880], format: NA NA ...\n $ fecha_cui_intensivo           : Date[1:5245880], format: NA NA ...\n $ fecha_fallecimiento           : Date[1:5245880], format: NA NA ...\n $ clasificacion                 : chr [1:5245880] \"Caso confirmado por laboratorio - No activo (por tiempo de evolución)\" \"Caso confirmado por laboratorio - No activo (por tiempo de evolución)\" \"Caso confirmado por laboratorio - No activo (por tiempo de evolución)\" \"Caso sospechoso - No Activo - Con muestra sin resultado concluyente\" ...\n $ clasificacion_resumen         : chr [1:5245880] \"Confirmado\" \"Confirmado\" \"Confirmado\" \"Sospechoso\" ...\n```\n:::\n:::\n\n\nEn total, el dataset presenta información para 5245861 casos diferentes. Las variables disponibles se encuentran descriptas en @tbl-vars de acuerdo a la información obtenida desde fuentes oficiales. De ellas fueron elegidas un porcentaje.\n\nEsto va a aplicar a ambos subdatasets.\n\n\n|  Titulo de la columna             |    Tipo de dato          |  Descripción                               |  \n|:----------------------------------|:-------------------------|:-------------------------------------------|\n| `id_evento_caso`                  | Número entero (integer)  | Numero de caso                             | \n| `sexo`                            | Texto (string)           | Sexo                                       |  \n| `edad`                            | Número entero (integer)  | Edad                                       |  \n| `edad_años_meses`                 | Texto (string)           | Edad indicada en meses o años              |  \n| `residencia_pais_nombre`          | Texto (string)           | País de residencia                         |   \n| `residencia_provincia_nombre`     | Texto (string)           | Provincia de residencia                    | \n| `residencia_departamento_nombre`  | Texto (string)           | Departamento de residencia                 |  \n| `carga_provincia_nombre`          | Texto (string)           | Provincia de establecimiento de carga      |  \n| `fecha_inicio_sintomas`           | Fecha ISO-8601 (date)    | Fecha de inicio de síntomas                |   \n| `fecha_apertura`                  | Fecha ISO-8601 (date)    | Fecha de apertura del caso                 |  \n| `sepi_apertura`                   | Número entero (integer)  | Semana Epidemiológica de fecha de apertura |   \n| `fecha_internacion`               | Fecha ISO-8601 (date)    | Fecha de internación                       | \n| `cuidado_intensivo`               | Fecha ISO-8601 (date)    | Fecha de ingreso a cuidado intensivo en el caso de corresponder |  \n| `fallecido`                       | Texto (string)           | Indicación de fallecido                    |  \n| `fecha_fallecimiento`             | Fecha ISO-8601 (date)    | Fecha de fallecimiento                     |  \n| `asistencia_respiratoria_mecanica`| Texto (string)           | Indicación si requirió asistencia respiratoria mecánica |   \n| `carga_provincia_id`              | Número entero (integer)  | Código de Provincia de carga               |  \n| `origen_financiamiento`           | Texto (string)           | Origen de financiamiento                   |\n| `clasificacion`                   | Texto (string)           | Clasificación manual del registro          |\n| `clasificacion_resumen`           | Texto (string)           | Clasificación del caso                     |\n| `residencia_provincia_id`         | Número entero (integer)  | Código de Provincia de residencia          |\n| `fecha_diagnostico`               | Tiempo ISO-8601 (time)   | Fecha de diagnóstico                       |\n| `residencia_departamento_id`      | Número entero (integer)  | Código de Departamento de residencia       |\n| `ultima_actualizacion`            | Fecha ISO-8601 (date)    | Última actualización                       |\n\n: Variables provistas en el dataset de la Dirección Nacional de Epidemiología y Análisis de Situación de Salud {#tbl-vars} \n\n**Datos faltantes**\n\n`fecha_apertura` (variable descartada) es la unica variable que reporta una fecha para todas las observaciones. `fecha_diagnostico` y `fecha_inicio_sintomas` NO PRESENTAN datos para todas las observaciones. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(covid_casos_muestra)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n id_evento_caso          edad         edad_años_meses        sexo          \n Min.   :  733774   Min.   : -84.00   Length:5245880     Length:5245880    \n 1st Qu.: 8678407   1st Qu.:  27.00   Class :character   Class :character  \n Median :16534314   Median :  38.00   Mode  :character   Mode  :character  \n Mean   :17505517   Mean   :  39.63                                        \n 3rd Qu.:27367564   3rd Qu.:  51.00                                        \n Max.   :33222629   Max.   :2023.00                                        \n                    NA's   :1424                                           \n carga_provincia_nombre residencia_pais_nombre residencia_provincia_nombre\n Length:5245880         Length:5245880         Length:5245880             \n Class :character       Class :character       Class :character           \n Mode  :character       Mode  :character       Mode  :character           \n                                                                          \n                                                                          \n                                                                          \n                                                                          \n residencia_departamento_nombre fecha_inicio_sintomas fecha_diagnostico   \n Length:5245880                 Min.   :2020-01-01    Min.   :1202-01-07  \n Class :character               1st Qu.:2020-12-05    1st Qu.:2021-03-20  \n Mode  :character               Median :2021-05-05    Median :2021-07-19  \n                                Mean   :2021-05-13    Mean   :2021-07-22  \n                                3rd Qu.:2021-12-28    3rd Qu.:2022-01-13  \n                                Max.   :2022-06-04    Max.   :2022-06-04  \n                                NA's   :2720185       NA's   :825927      \n fecha_internacion    fecha_cui_intensivo  fecha_fallecimiento \n Min.   :2020-01-01   Min.   :2020-03-04   Min.   :2020-03-07  \n 1st Qu.:2020-08-08   1st Qu.:2020-08-31   1st Qu.:2020-09-30  \n Median :2020-12-28   Median :2021-02-15   Median :2021-04-06  \n Mean   :2021-01-18   Mean   :2021-02-05   Mean   :2021-03-04  \n 3rd Qu.:2021-05-24   3rd Qu.:2021-05-27   3rd Qu.:2021-06-10  \n Max.   :2022-06-04   Max.   :2022-06-04   Max.   :2022-06-04  \n NA's   :5103454      NA's   :5221684      NA's   :5169727     \n clasificacion      clasificacion_resumen\n Length:5245880     Length:5245880       \n Class :character   Class :character     \n Mode  :character   Mode  :character     \n                                         \n                                         \n                                         \n                                         \n```\n:::\n:::\n\n\n### Total de casos de cada clasificación para CABA y Buenos Aires\n\nLa provincia de Buenos Aires tiene un mayor número de casos reportados en \ntotal para el período estudiado.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n covid_casos_muestra |> \n  filter(carga_provincia_nombre %in% c('CABA', 'Buenos Aires')) |> # este filtro tiene sentido porque considere los casos de residentes en caba y baires que fueron cargados en otras provincias tambien\n  select(-1) |> \n  count(carga_provincia_nombre, clasificacion_resumen) |> \n  ggplot() +\n  geom_col(aes(x = carga_provincia_nombre,\n               y = n,\n               fill = clasificacion_resumen)) +\n  scale_fill_viridis_d(option = \"C\") +\n  theme_minimal() +\n    ylab('Cantidad de observaciones') +\n    xlab('carga_provincia_nombre')\n```\n\n::: {.cell-output-display}\n![](analisis_datos_covid_files/figure-html/unnamed-chunk-4-1.png){width=550}\n:::\n:::\n\n\n### Distribución de NAs en las distintas fechas reportadas\n\nDebido a que la información de movilidad ciudadana se encuentra reportada por \ndía es importante poder obtener una fecha asociada a cada observación.\n\n* `fecha_diagnostico` y `fecha_inicio_sintomas` son las variables con mayor\nnúmero de observaciones y las más relevantes a nivel epidemiológico.\n\n* `fecha_cui_intensivo` presenta menor cantidad de observaciones que \n`fecha_fallecido`. Esto podria ser por falta de datos o por muertes que se\ndieron sin llegar a internacion.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_fechas <- covid_casos_muestra |> \n  select(starts_with('fecha_')) |> \n  pivot_longer(1:5,\n               names_to = 'names',\n               values_to = 'values'\n                ) |> \n  group_by(names) |> \n  summarize(n = sum(!is.na(values))) \n\n\n  ggplot(obs_fechas) +\n  geom_col(aes(x = fct_reorder(names, n),\n           y = n),\n           fill = viridis::magma(3)[2]) +\n    theme_minimal() +\n    coord_flip() +\n    xlab('Variables') +\n    ylab('Datos presentes en la base de datos')\n```\n\n::: {.cell-output-display}\n![Cantidad de casos de COVID-19 reportados ](analisis_datos_covid_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\n\n## Análisis de `fecha_inicio_sintomas` y `fecha_diagnostico`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncase_both_na <- sum(is.na(covid_casos_muestra$fecha_inicio_sintomas) & is.na(covid_casos_muestra$fecha_diagnostico))\n\ncase_sintomas_na <- sum(is.na(covid_casos_muestra$fecha_inicio_sintomas) & !is.na(covid_casos_muestra$fecha_diagnostico)) \n\ncase_diagnostico_na <- sum(!is.na(covid_casos_muestra$fecha_inicio_sintomas) & is.na(covid_casos_muestra$fecha_diagnostico)) \n\ncase_both_filled <- sum(!is.na(covid_casos_muestra$fecha_inicio_sintomas) & !is.na(covid_casos_muestra$fecha_diagnostico))\n\n# Create a table with the counts\ntable_data <- data.frame(casos = c(\"ambas_columnas_na\", \"fecha_inicio_sintomas_na\", \n                                   \"fecha_diagnostico_na\",\"ambas_columnas_completas\"),\n                         obs = c(case_both_na, case_sintomas_na,\n                                   case_diagnostico_na, case_both_filled)\n) |> \n  mutate(porcentaje = round((100*obs)/nrow(covid_casos_muestra), digit = 1))\n\n\n\n# chequeo que la cantidad de valores reportados en la tabla\n# equivale al total de observaciones\nif(sum(table_data$obs) == nrow(covid_casos_muestra)){\n  \n  kable(table_data)\n}\n```\n\n::: {.cell-output-display}\n|casos                    |     obs| porcentaje|\n|:------------------------|-------:|----------:|\n|ambas_columnas_na        |  284549|        5.4|\n|fecha_inicio_sintomas_na | 2435636|       46.4|\n|fecha_diagnostico_na     |  541378|       10.3|\n|ambas_columnas_completas | 1984317|       37.8|\n:::\n:::\n\n\n\n###  CASO 1: fecha de inicio de sintomas y fecha de diagnostico no reportadas\n\nEsto es el 5.4 % del total de la base de datos.\n\nLa mayoría de estos casos son `sospechosos`, posibles falsos negativos. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid_casos_muestra |> \n  filter(is.na(covid_casos_muestra$fecha_inicio_sintomas) & is.na(covid_casos_muestra$fecha_diagnostico)) |> \n  select(clasificacion, clasificacion_resumen) |> \n  group_by(clasificacion_resumen, clasificacion) |> \n  summarize(obs = n()) |> \n  arrange(desc(obs)) |> \n  head() |> \n  kable()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'clasificacion_resumen'. You can override\nusing the `.groups` argument.\n```\n:::\n\n::: {.cell-output-display}\n|clasificacion_resumen |clasificacion                                                                             |    obs|\n|:---------------------|:-----------------------------------------------------------------------------------------|------:|\n|Sospechoso            |Caso sospechoso - No Activo - Con muestra sin resultado concluyente                       | 106623|\n|Confirmado            |Caso confirmado por criterio clínico-epidemiológico - No activo (por tiempo de evolución) |  77031|\n|Sospechoso            |Caso sospechoso - No Activo - Sin muestra                                                 |  61349|\n|Probable              |Caso probable por Autotest - No Activo (por tiempo de evolución)                          |  23485|\n|Probable              |Caso probable por Autotest - Activo                                                       |   7336|\n|Sospechoso            |Caso sospechoso - Activo Internado - Con muestra sin resultado concluyente                |   2061|\n\n\n\nClasificación de los casos donde fecha_inicio_sintomas y fecha_diagnostico fueron no reportadas\n:::\n:::\n\n\n###  CASO 2: fecha de inicio de sintomas reportada y fecha de diagnostico ausente\n\nEsto es el 46.4 % del total de la base de datos.\n\nLa mayoría de estas observaciones representan pacientes con casos confirmados por\nlaboratorio.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid_casos_muestra |> \n  filter(is.na(covid_casos_muestra$fecha_inicio_sintomas) & !is.na(covid_casos_muestra$fecha_diagnostico)) |> \n  select(clasificacion, clasificacion_resumen) |> \n  group_by(clasificacion_resumen, clasificacion) |> \n  summarize(obs = n()) |> \n  arrange(desc(obs)) |>\n  head() |> \n  kable()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'clasificacion_resumen'. You can override\nusing the `.groups` argument.\n```\n:::\n\n::: {.cell-output-display}\n|clasificacion_resumen |clasificacion                                                                             |     obs|\n|:---------------------|:-----------------------------------------------------------------------------------------|-------:|\n|Confirmado            |Caso confirmado por laboratorio - No activo (por tiempo de evolución)                     | 2342696|\n|Confirmado            |Caso confirmado por laboratorio - No Activo por criterio de laboratorio                   |   45219|\n|Confirmado            |Caso confirmado por laboratorio - Activo                                                  |   27943|\n|Confirmado            |Caso confirmado por criterio clínico-epidemiológico - No activo (por tiempo de evolución) |    8837|\n|Confirmado            |Caso confirmado por laboratorio - Fallecido                                               |    7814|\n|Sospechoso            |Caso con resultado negativo-no conclusivo - Activo                                        |    2097|\n\n\n\nClasificación de los casos donde solo fecha_inicio_sintomas fue reportada.\n:::\n:::\n\n\n###  CASO 3: fecha de inicio de sintomas ausente y fecha de diagnostico reportada\n\nEsto es el  % del total de la base de datos.\n\nEn este caso, en su mayoria son los casos que fueron confirmados por criterio \nclínico-epidemiologico.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid_casos_muestra |> \n  filter(!is.na(covid_casos_muestra$fecha_inicio_sintomas) & is.na(covid_casos_muestra$fecha_diagnostico)) |> \n  select(clasificacion, clasificacion_resumen) |> \n  group_by(clasificacion_resumen, clasificacion) |> \n  summarize(obs = n()) |> \n  arrange(desc(obs)) |> \n  head() |> \n  kable()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'clasificacion_resumen'. You can override\nusing the `.groups` argument.\n```\n:::\n\n::: {.cell-output-display}\n|clasificacion_resumen |clasificacion                                                                             |    obs|\n|:---------------------|:-----------------------------------------------------------------------------------------|------:|\n|Confirmado            |Caso confirmado por criterio clínico-epidemiológico - No activo (por tiempo de evolución) | 268559|\n|Sospechoso            |Caso sospechoso - No Activo - Sin muestra                                                 | 130728|\n|Sospechoso            |Caso sospechoso - No Activo - Con muestra sin resultado concluyente                       | 109266|\n|Sospechoso            |Caso sospechoso - Activo Internado - Sin muestra                                          |  11534|\n|Sospechoso            |Caso sospechoso - Activo Internado - Con muestra sin resultado concluyente                |  10104|\n|Confirmado            |Caso confirmado por criterio clínico - epidemiológico -  Activo internado                 |   3803|\n\n\n\nClasificación de los casos donde solo fecha_diagnostico fue reportada.\n:::\n:::\n\n\n###  CASO 4: fecha de inicio de sintomas y fecha de diagnostico reportadas\n\nEsto es el 37.8 % del total de la base de datos.\n\nEn este caso, en su mayoría son los casos que fueron confirmados por laboratorio.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid_casos_muestra |> \n  filter(!is.na(covid_casos_muestra$fecha_inicio_sintomas) & !is.na(covid_casos_muestra$fecha_diagnostico)) |> \n  select(clasificacion, clasificacion_resumen) |> \n  group_by(clasificacion_resumen, clasificacion) |> \n  summarize(obs = n()) |> \n  arrange(desc(obs)) |> \n  head() |> \n  kable()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'clasificacion_resumen'. You can override\nusing the `.groups` argument.\n```\n:::\n\n::: {.cell-output-display}\n|clasificacion_resumen |clasificacion                                                                             |     obs|\n|:---------------------|:-----------------------------------------------------------------------------------------|-------:|\n|Confirmado            |Caso confirmado por laboratorio - No activo (por tiempo de evolución)                     | 1825253|\n|Confirmado            |Caso confirmado por laboratorio - Fallecido                                               |   64442|\n|Confirmado            |Caso confirmado por laboratorio - No Activo por criterio de laboratorio                   |   50849|\n|Confirmado            |Caso confirmado por criterio clínico-epidemiológico - No activo (por tiempo de evolución) |   35131|\n|Confirmado            |Caso confirmado por laboratorio - Activo                                                  |    4687|\n|Sospechoso            |Caso con resultado negativo-no conclusivo - Activo                                        |    1054|\n\n\n\nClasificación de los casos donde fecha_inicio_sintomas y fecha_diagnostico fueron reportadas.\n:::\n:::\n\n\n#### Diferencia de días entre `fecha_inicio_sintomas` y `fecha_diagnostico`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndif_dias_total_casos <- covid_casos_muestra |> \n  dplyr::filter(carga_provincia_nombre %in% c('CABA', 'Buenos Aires')) |> \n  mutate(dias_caso = as.numeric(difftime(fecha_diagnostico, # time1\n                                         fecha_inicio_sintomas, # time2\n                                         units=\"days\"))) # logica: time1 - time2\n\ndif_dias <- dif_dias_total_casos |> \n   dplyr::filter(!is.na(fecha_inicio_sintomas) & !is.na(fecha_diagnostico))  # CASO 4\n\ndif_dias\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1,973,695 × 16\n   id_evento_caso  edad edad_años_meses sexo  carga_provincia_nombre\n            <int> <int> <chr>           <chr> <chr>                 \n 1       10000079    55 Años            M     Buenos Aires          \n 2       10000084    47 Años            M     Buenos Aires          \n 3       10000087    45 Años            F     Buenos Aires          \n 4       10000093    48 Años            M     Buenos Aires          \n 5       10000099    54 Años            F     Buenos Aires          \n 6        1000012    48 Años            M     CABA                  \n 7       10000143    50 Años            M     Buenos Aires          \n 8        1000015    31 Años            F     Buenos Aires          \n 9       10000157    25 Años            M     Buenos Aires          \n10       10000187    32 Años            M     Buenos Aires          \n# ℹ 1,973,685 more rows\n# ℹ 11 more variables: residencia_pais_nombre <chr>,\n#   residencia_provincia_nombre <chr>, residencia_departamento_nombre <chr>,\n#   fecha_inicio_sintomas <date>, fecha_diagnostico <date>,\n#   fecha_internacion <date>, fecha_cui_intensivo <date>,\n#   fecha_fallecimiento <date>, clasificacion <chr>,\n#   clasificacion_resumen <chr>, dias_caso <dbl>\n```\n:::\n:::\n\n\nLos casos tienen un rango que va del positivo al negativo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrange(dif_dias$dias_caso)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -7304   828\n```\n:::\n:::\n\n\nSi grafico, observo que la gran mayoria de los casos cae entre 0 a 10 dias.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplotly(\ndif_dias |> \n  filter(dias_caso < 30, dias_caso > -7) |> \n  group_by(dias_caso, carga_provincia_nombre) |> \n  count() |> \n  ggplot(aes(x = dias_caso,\n             y = n,\n             fill = carga_provincia_nombre)) +\n  geom_col() +\n  scale_fill_viridis_d()+\n  theme_minimal() +\n  ylab('Cantidad de observaciones') +\n  xlab('Diferencia entre fecha_inicio_sintomas y fecha_diagnostico')\n\n)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-3d65672a8f9557cdeb1e\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-3d65672a8f9557cdeb1e\">{\"x\":{\"data\":[{\"orientation\":\"v\",\"width\":[0.90000000000000036,0.90000000000000036,0.90000000000000036,0.90000000000000036,0.90000000000000013,0.89999999999999991,0.90000000000000002,0.89999999999999991,0.90000000000000013,0.90000000000000036,0.90000000000000036,0.90000000000000036,0.90000000000000036,0.90000000000000036,0.89999999999999947,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858],\"base\":[246,304,335,481,670,1344,33817,54229,78576,83164,54695,31102,18421,14589,8855,5712,4349,3026,1978,1667,1589,1220,882,781,641,470,492,463,464,336,282,248,236,211,196,214],\"x\":[-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29],\"y\":[366,462,517,664,975,1828,78256,152167,255087,290846,230733,159629,103442,70684,47695,31830,21530,15433,11210,8745,7181,5843,4598,3723,2861,2284,1906,1700,1523,1246,1112,943,860,802,703,564],\"text\":[\"dias_caso: -6<br />n:    366<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: -5<br />n:    462<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: -4<br />n:    517<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: -3<br />n:    664<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: -2<br />n:    975<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: -1<br />n:   1828<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso:  0<br />n:  78256<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso:  1<br />n: 152167<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso:  2<br />n: 255087<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso:  3<br />n: 290846<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso:  4<br />n: 230733<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso:  5<br />n: 159629<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso:  6<br />n: 103442<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso:  7<br />n:  70684<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso:  8<br />n:  47695<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso:  9<br />n:  31830<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 10<br />n:  21530<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 11<br />n:  15433<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 12<br />n:  11210<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 13<br />n:   8745<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 14<br />n:   7181<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 15<br />n:   5843<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 16<br />n:   4598<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 17<br />n:   3723<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 18<br />n:   2861<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 19<br />n:   2284<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 20<br />n:   1906<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 21<br />n:   1700<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 22<br />n:   1523<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 23<br />n:   1246<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 24<br />n:   1112<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 25<br />n:    943<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 26<br />n:    860<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 27<br />n:    802<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 28<br />n:    703<br />carga_provincia_nombre: Buenos Aires\",\"dias_caso: 29<br />n:    564<br />carga_provincia_nombre: Buenos Aires\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(68,1,84,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"transparent\"}},\"name\":\"Buenos Aires\",\"legendgroup\":\"Buenos Aires\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.90000000000000036,0.90000000000000036,0.90000000000000036,0.90000000000000036,0.90000000000000013,0.89999999999999991,0.90000000000000002,0.89999999999999991,0.90000000000000013,0.90000000000000036,0.90000000000000036,0.90000000000000036,0.90000000000000036,0.90000000000000036,0.89999999999999947,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858],\"base\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],\"x\":[-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29],\"y\":[246,304,335,481,670,1344,33817,54229,78576,83164,54695,31102,18421,14589,8855,5712,4349,3026,1978,1667,1589,1220,882,781,641,470,492,463,464,336,282,248,236,211,196,214],\"text\":[\"dias_caso: -6<br />n:    246<br />carga_provincia_nombre: CABA\",\"dias_caso: -5<br />n:    304<br />carga_provincia_nombre: CABA\",\"dias_caso: -4<br />n:    335<br />carga_provincia_nombre: CABA\",\"dias_caso: -3<br />n:    481<br />carga_provincia_nombre: CABA\",\"dias_caso: -2<br />n:    670<br />carga_provincia_nombre: CABA\",\"dias_caso: -1<br />n:   1344<br />carga_provincia_nombre: CABA\",\"dias_caso:  0<br />n:  33817<br />carga_provincia_nombre: CABA\",\"dias_caso:  1<br />n:  54229<br />carga_provincia_nombre: CABA\",\"dias_caso:  2<br />n:  78576<br />carga_provincia_nombre: CABA\",\"dias_caso:  3<br />n:  83164<br />carga_provincia_nombre: CABA\",\"dias_caso:  4<br />n:  54695<br />carga_provincia_nombre: CABA\",\"dias_caso:  5<br />n:  31102<br />carga_provincia_nombre: CABA\",\"dias_caso:  6<br />n:  18421<br />carga_provincia_nombre: CABA\",\"dias_caso:  7<br />n:  14589<br />carga_provincia_nombre: CABA\",\"dias_caso:  8<br />n:   8855<br />carga_provincia_nombre: CABA\",\"dias_caso:  9<br />n:   5712<br />carga_provincia_nombre: CABA\",\"dias_caso: 10<br />n:   4349<br />carga_provincia_nombre: CABA\",\"dias_caso: 11<br />n:   3026<br />carga_provincia_nombre: CABA\",\"dias_caso: 12<br />n:   1978<br />carga_provincia_nombre: CABA\",\"dias_caso: 13<br />n:   1667<br />carga_provincia_nombre: CABA\",\"dias_caso: 14<br />n:   1589<br />carga_provincia_nombre: CABA\",\"dias_caso: 15<br />n:   1220<br />carga_provincia_nombre: CABA\",\"dias_caso: 16<br />n:    882<br />carga_provincia_nombre: CABA\",\"dias_caso: 17<br />n:    781<br />carga_provincia_nombre: CABA\",\"dias_caso: 18<br />n:    641<br />carga_provincia_nombre: CABA\",\"dias_caso: 19<br />n:    470<br />carga_provincia_nombre: CABA\",\"dias_caso: 20<br />n:    492<br />carga_provincia_nombre: CABA\",\"dias_caso: 21<br />n:    463<br />carga_provincia_nombre: CABA\",\"dias_caso: 22<br />n:    464<br />carga_provincia_nombre: CABA\",\"dias_caso: 23<br />n:    336<br />carga_provincia_nombre: CABA\",\"dias_caso: 24<br />n:    282<br />carga_provincia_nombre: CABA\",\"dias_caso: 25<br />n:    248<br />carga_provincia_nombre: CABA\",\"dias_caso: 26<br />n:    236<br />carga_provincia_nombre: CABA\",\"dias_caso: 27<br />n:    211<br />carga_provincia_nombre: CABA\",\"dias_caso: 28<br />n:    196<br />carga_provincia_nombre: CABA\",\"dias_caso: 29<br />n:    214<br />carga_provincia_nombre: CABA\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(253,231,37,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"transparent\"}},\"name\":\"CABA\",\"legendgroup\":\"CABA\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.228310502283108,\"r\":7.3059360730593621,\"b\":40.182648401826498,\"l\":60.639269406392714},\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-8.245000000000001,31.244999999999997],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"10\",\"20\",\"30\"],\"tickvals\":[0,10,20,30.000000000000004],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"10\",\"20\",\"30\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Diferencia entre fecha_inicio_sintomas y fecha_diagnostico\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-18700.5,392710.5],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"100000\",\"200000\",\"300000\"],\"tickvals\":[0,100000,200000.00000000003,300000],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"100000\",\"200000\",\"300000\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Cantidad de observaciones\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"title\":{\"text\":\"carga_provincia_nombre\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"5f3635ae968d\":{\"x\":{},\"y\":{},\"fill\":{},\"type\":\"bar\"}},\"cur_data\":\"5f3635ae968d\",\"visdat\":{\"5f3635ae968d\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nPeríodo entre fecha_inicio_sintomas y fecha_diagnostico reportado para Buenos Aires y CABA, en los casos donde ambos valores fueron reportados\n:::\n:::\n\n\n## Base de datos final\n\n- Debido a que los datos de movilidad ciudadana solo son para el año 2020,\nse limita la base a ese periodo.\n- Considerando los casos descriptos anteriormente se tomaran las decisiones \nresumidas @tbl-desicion para la creación de una nueva variable `fecha_enfermo`:\n\n\n|Caso |    Descripcion                                                 |  fecha_enfermo                             |  \n|:--|:-----------------------------------------------------------------|:---------------------------------------|\n| 1 | `fecha_inicio_sintomas` y `fecha_diagnostico` no reportadas      | Remover casos                     |   \n| 2 | `fecha_inicio_sintomas` reportada y `fecha_diagnostico` ausente  | Se considera `fecha_diagnostico`   |\n| 3 | `fecha_inicio_sintomas` ausente y `fecha_diagnostico` reportada  | Se considera `fecha_inicio_sintomas`   |\n| 4 | `fecha_inicio_sintomas` y `fecha_diagnostico` reportadas         | Se conserva `fecha_inicio_sintoma` |  \n\n: Desiciones para la creación de la variable `fecha_enfermo` {#tbl-desicion}\n\n- Para el caso 4, se eliminaron tambien los casos donde la diferencia entre\n`fecha_inicio_sintomas` y `fecha_diagnostico` era mayor a 30 o menor a -7.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# periodo de analisis\ncovid_inicio <- ymd(\"2020-03-01\")\ncovid_final <- ymd(\"2022-03-31\")\n\nperiodo <- function(x) {\n  covid_inicio <= x & covid_final >= x\n}\n\ncovid_casos_muestra <-  covid_casos_muestra |> \n  filter(if_all(starts_with('fecha_'),\n               ~ is.na(.x) | covid_inicio <= .x & covid_final >= .x))     \n\nbase_covid_completa <- dif_dias_total_casos |> \n                          # elimino casos donde la diferencia de dias entre \n                          # fecha de sintomas y diagnostico es muy extrema\n                          filter(dias_caso < 30,\n                                 dias_caso > -7) |> \n                          mutate(fecha_enfermo = case_when(\n                            # CASO 1\n                              !is.na(fecha_inicio_sintomas) &\n                              !is.na(fecha_diagnostico) ~ as.character(fecha_inicio_sintomas),\n                            # CASO 2\n                              is.na(fecha_inicio_sintomas) & \n                              !is.na(fecha_diagnostico) ~ as.character(fecha_diagnostico),\n                            # CASO 3\n                              !is.na(fecha_inicio_sintomas) &\n                              is.na(fecha_diagnostico) ~ as.character(fecha_inicio_sintomas),\n                            # CASO 4\n                              is.na(fecha_inicio_sintomas) &\n                              is.na(fecha_diagnostico) ~ NA_character_)) |> \n                              filter(fecha_enfermo <= as.Date('2020-12-31'),\n                                     fecha_enfermo >= as.Date('2020-03-01')) \n\n\nbase_covid_completa <- base_covid_completa |> \n                          drop_na(fecha_enfermo) # remuevo el caso 1\n\nhead(base_covid_completa)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 17\n  id_evento_caso  edad edad_años_meses sexo  carga_provincia_nombre\n           <int> <int> <chr>           <chr> <chr>                 \n1        1000012    48 Años            M     CABA                  \n2        1000015    31 Años            F     Buenos Aires          \n3        1000024    63 Años            M     CABA                  \n4        1000025    23 Años            M     Buenos Aires          \n5        1000037    77 Años            F     CABA                  \n6        1000052    31 Años            F     Buenos Aires          \n# ℹ 12 more variables: residencia_pais_nombre <chr>,\n#   residencia_provincia_nombre <chr>, residencia_departamento_nombre <chr>,\n#   fecha_inicio_sintomas <date>, fecha_diagnostico <date>,\n#   fecha_internacion <date>, fecha_cui_intensivo <date>,\n#   fecha_fallecimiento <date>, clasificacion <chr>,\n#   clasificacion_resumen <chr>, dias_caso <dbl>, fecha_enfermo <chr>\n```\n:::\n\n```{.r .cell-code}\n# guardo la base\nwrite_parquet(base_covid_completa, \"data/procesada/covid_casos_baires_geocovid.parquet\")\n```\n:::",
    "supporting": [
      "analisis_datos_covid_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/htmlwidgets-1.6.2/htmlwidgets.js\"></script>\n<script src=\"site_libs/plotly-binding-4.10.3.9000/plotly.js\"></script>\n<script src=\"site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\n<link href=\"site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}